# fly.toml app configuration file generated for paycore-api on 2025-11-07T13:09:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'paycore-api'
primary_region = 'ams'
console_command = '/app/manage.py shell'

[build]

[deploy]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  # Add health checks to prevent premature restarts
  [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    method = "GET"
    path = "/api/v1/healthcheck/"
    timeout = "15s"
    type = "http"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/staticfiles'
  url_prefix = '/static/'
